---
title: "Introduction to Habitat Condition Assessment System (HCAS)"
author: "Roozbeh Valavi, ..."
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Introduction to Habitat Condition Assessment System (HCAS)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## Introduction


## HCAS steps

Diagram here:




## Getting example data

```{r}
# xy_train <- read.csv("P:/BMS/pacakge_data/samples/train_xy.csv")
# obs_train <- read.csv("P:/BMS/pacakge_data/samples/train_obs.csv")
# pred_train <- read.csv("P:/BMS/pacakge_data/samples/train_pred.csv")
# 
# full_data <- cbind(xy_train, obs_train, pred_train)

```


## Reference density calculation


```{r, warning=FALSE, message=FALSE, fig.width=5, fig.height=4}
# ref_density <- ClassicHCAS::ref_density(
#   data = full_data,
#   radius_km = 1000,
#   bin_width = 0.03
# )
# 
# plot(ref_density)

```


## Reference density normalisation


```{r, fig.width=5, fig.height=4}
# norm <- ClassicHCAS::normalise(x = ref_density)
# 
# plot(norm)

```


## Benchmarking


```{r}


```


## Calibration



