# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bench_cpp <- function(raster_vals, sample_vals, histogram, xy_stats, xy_penalty = 0.0, geographic = FALSE, radius_km = 200, k_env = 50L, k_rs = 20L, bin_width = 0.05, bin_num = 400L, offset = 0L, confidence = 0.5, lambda = 2.0, exclude_slef = TRUE, make_su = FALSE, num_threads = -1L) {
    .Call(`_ClassicHCAS_bench_cpp`, raster_vals, sample_vals, histogram, xy_stats, xy_penalty, geographic, radius_km, k_env, k_rs, bin_width, bin_num, offset, confidence, lambda, exclude_slef, make_su, num_threads)
}

density_cpp <- function(rast, xy, radius_km = 200.0, geographic = FALSE, num_threads = -1L) {
    .Call(`_ClassicHCAS_density_cpp`, rast, xy, radius_km, geographic, num_threads)
}

histo_cpp <- function(rs_vals, pr_vals, xy_vals, radius_km = 1000.0, bin_width = 0.05, bin_num = 650L, geographic = FALSE, num_threads = -1L) {
    .Call(`_ClassicHCAS_histo_cpp`, rs_vals, pr_vals, xy_vals, radius_km, bin_width, bin_num, geographic, num_threads)
}

norm_cpp <- function(x, trim_size = 400L, offset = 0L) {
    .Call(`_ClassicHCAS_norm_cpp`, x, trim_size, offset)
}

