# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bench_cpp <- function(raster_vals, sample_vals, ref_density, xy_stats, xy_penalty = 0.0, geographic = FALSE, radius_km = 200, k_env = 70L, k_rs = 10L, bin_width = 0.05, bin_num = 400L, offset = 0L, confidence = 0.5, lambda = 1.0, exclude_slef = TRUE, temporal_weights = NULL, make_su = FALSE, num_threads = -1L, kernel = "gaussian", boost = NULL) {
    .Call(`_ClassicHCAS_bench_cpp`, raster_vals, sample_vals, ref_density, xy_stats, xy_penalty, geographic, radius_km, k_env, k_rs, bin_width, bin_num, offset, confidence, lambda, exclude_slef, temporal_weights, make_su, num_threads, kernel, boost)
}

norm_cpp <- function(x, trim_size = 400L, offset = 0L) {
    .Call(`_ClassicHCAS_norm_cpp`, x, trim_size, offset)
}

radial_count_cpp <- function(rast, xy, radius_km = 200.0, geographic = FALSE, num_threads = -1L) {
    .Call(`_ClassicHCAS_radial_count_cpp`, rast, xy, radius_km, geographic, num_threads)
}

ref_density_cpp <- function(rs_vals, pr_vals, xy_vals, radius_km = 1000.0, bin_width = 0.05, bin_num = 650L, geographic = FALSE, num_threads = -1L) {
    .Call(`_ClassicHCAS_ref_density_cpp`, rs_vals, pr_vals, xy_vals, radius_km, bin_width, bin_num, geographic, num_threads)
}

reference_use_cpp <- function(target_vals, sample_vals, ref_density, xy_stats, xy_penalty = 0.0, geographic = FALSE, radius_km = 200, k_env = 70L, k_rs = 10L, bin_width = 0.05, bin_num = 400L, offset = 0L, confidence = 0.5, lambda = 1.0, exclude_slef = TRUE, num_threads = -1L, weighted_max = FALSE, kernel = "gaussian", boost = NULL) {
    .Call(`_ClassicHCAS_reference_use_cpp`, target_vals, sample_vals, ref_density, xy_stats, xy_penalty, geographic, radius_km, k_env, k_rs, bin_width, bin_num, offset, confidence, lambda, exclude_slef, num_threads, weighted_max, kernel, boost)
}

tiling_cpp <- function(x, n_tiles, method = "best", exact = TRUE) {
    .Call(`_ClassicHCAS_tiling_cpp`, x, n_tiles, method, exact)
}

variable_importance_cpp <- function(target_vals, sample_vals, ref_density, xy_stats, xy_penalty = 0.0, geographic = FALSE, radius_km = 200, k_env = 70L, k_rs = 10L, bin_width = 0.05, bin_num = 400L, offset = 0L, lambda = 1.0, epsilon = 1e-6, output = "importance", exclude_slef = TRUE, num_threads = -1L, kernel = "gaussian", boost = NULL) {
    .Call(`_ClassicHCAS_variable_importance_cpp`, target_vals, sample_vals, ref_density, xy_stats, xy_penalty, geographic, radius_km, k_env, k_rs, bin_width, bin_num, offset, lambda, epsilon, output, exclude_slef, num_threads, kernel, boost)
}

